version: '3.1'
services:
  enpyre_play:
    container_name: enpyre_play
    env_file: .env
    build:
      context: .
      args:
        ENVIRONMENT: development
    volumes:
      - .:/code/.
    ports:
      - "8000:8000"
    depends_on:
      - enpyre_postgres
      - enpyre_rabbitmq
    networks:
      - default
  enpyre_postgres:
    image: postgres:14-alpine
    container_name: enpyre_postgres
    volumes:
      - ./.ignore/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: enpyre
      POSTGRES_PASSWORD: enpyre
      POSTGRES_DB: enpyre_db
    ports:
      - "5432:5432"
    networks:
      - default
  enpyre_rabbitmq:
    image: rabbitmq:3.10.10-management-alpine
    container_name: enpyre_rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=enpyre
      - RABBITMQ_DEFAULT_PASS=enpyre
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - default
    logging:
      driver: none
  enpyre_celery:
    env_file: .env
    build:
      context: .
      args:
        ENVIRONMENT: development
        CELERY: true
    volumes:
      - .:/code/.
    command: ["./start_celery.sh"]
    depends_on:
      - enpyre_postgres
      - enpyre_rabbitmq
