# Generated by Django 4.1.6 on 2023-02-05 23:53

from django.conf import settings
from django.db import migrations, models

import enpyre_play.users.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_alter_project_options_project_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(
                on_delete=models.SET(enpyre_play.users.utils.get_sentinel_user),
                related_name='projects',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
