# Generated by Django 4.1.7 on 2023-03-27 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectsolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsolution',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='solutions',
                to='projects.project',
            ),
        ),
    ]
