# Generated by Django 4.1.7 on 2023-04-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_projectsolution_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.TextField(blank=True, help_text='Code of the project', null=True),
        ),
        migrations.AlterField(
            model_name='projectsolution',
            name='code',
            field=models.TextField(blank=True, help_text='Solution for the project', null=True),
        ),
    ]
