# Generated by Django 4.1.7 on 2023-02-20 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('score_type', models.CharField(max_length=10)),
                ('year', models.IntegerField(null=True)),
                ('month', models.IntegerField(null=True)),
                ('week', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['score_type', '-year', 'month', 'week'],
            },
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('total', models.IntegerField(default=0)),
                ('average', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                (
                    'score',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='user_scores',
                        to='scores.score',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                'ordering': ['-total'],
            },
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(
                fields=['score_type', '-year', 'month', 'week'], name='score_type_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(
                fields=('score_type', 'year', 'month', 'week'), name='unique_score'
            ),
        ),
        migrations.AddIndex(
            model_name='userscore',
            index=models.Index(fields=['-total'], name='user_total_idx'),
        ),
        migrations.AddIndex(
            model_name='userscore',
            index=models.Index(fields=['-average'], name='user_average_idx'),
        ),
    ]
