# Generated by Django 4.1.7 on 2023-02-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='average_count',
            field=models.IntegerField(default=0),
        ),
    ]
