# Generated by Django 4.1.6 on 2023-02-08 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import enpyre_play.users.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quizz',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Title of the quizz', max_length=100)),
                (
                    'description',
                    models.TextField(blank=True, help_text='Description of the quizz', null=True),
                ),
                ('quizz_type', models.CharField(help_text='Type of the quizz', max_length=100)),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=models.SET(enpyre_play.users.utils.get_sentinel_user),
                        related_name='quizzes',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuizzAnswer',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Title of the answer', max_length=100)),
                (
                    'content',
                    models.TextField(blank=True, help_text='Content of the answer', null=True),
                ),
                (
                    'is_correct',
                    models.BooleanField(default=False, help_text='Is the answer correct'),
                ),
                (
                    'score_amount',
                    models.IntegerField(default=0, help_text='Score amount of the answer'),
                ),
                ('position', models.IntegerField(default=0, help_text='Position of the answer')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuizzUserAnswer',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'answer',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='user_answers',
                        to='quizzes.quizzanswer',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='quizz_answers',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuizzQuestion',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Title of the question', max_length=100)),
                (
                    'content',
                    models.TextField(blank=True, help_text='Content of the question', null=True),
                ),
                ('position', models.IntegerField(default=0, help_text='Position of the question')),
                (
                    'quizz',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='questions',
                        to='quizzes.quizz',
                    ),
                ),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='quizzanswer',
            name='question',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='answers',
                to='quizzes.quizzquestion',
            ),
        ),
    ]
