# Generated by Django 4.1.6 on 2023-02-09 22:47

from django.db import migrations, models

import enpyre_play.quizzes.enums


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizz',
            name='quizz_type',
            field=models.CharField(
                default=enpyre_play.quizzes.enums.QuizzTypeSet['MULTIPLE_CHOICE'],
                help_text='Type of the quizz',
                max_length=100,
            ),
        ),
    ]
